### ISSUE TITLE
Add example data to the project

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/RocketFan#1]
We should add example data to the project; which will make it easier to work with when developing SwiftUI views. This example data should be taken from an actual JSON response from the SpaceX Api; so that we have "real" data to use. 

## Approach 

- [ ] Add an example JSON response from the service 
- [ ] Use Decodable to decode from JSON to actual objects 
- [ ] Add Launches JSOn response (More can be added as / when needed)

**Comment by squarefrog** [comment]
👍 Agreed. Although, I must say I'm a fan of Paul Hudson's recommendation of a static property.

```
struct Foo: Decodable {
  static let example = Bundle.main.decode([Foo].self, from: "Foo.json")
}
```
